# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      addresses:
      - 192.168.0.61/24
      gateway4: 192.168.0.1
      nameservers:
        addresses:
        - 192.168.0.61
        search: [ karengranadero.com ]      # DNS zone
  version: 2
